//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TupleGeo.Resources.Images.ColorRamps.TwoColors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TupleGeo.Resources.Images.ColorRamps.TwoColors.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_203_245_234_C2_048_207_146 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_203_245_234_C2_048_207_146", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_204_204_255_C2_000_000_224 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_204_204_255_C2_000_000_224", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_204_255_204_C2_014_204_014 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_204_255_204_C2_014_204_014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_211_223_232_C2_046_100_140 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_211_223_232_C2_046_100_140", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_215_240_175_C2_086_107_045 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_215_240_175_C2_086_107_045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_216_242_237_C2_021_079_074 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_216_242_237_C2_021_079_074", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_219_219_219_C2_069_069_069 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_219_219_219_C2_069_069_069", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_220_245_233_C2_034_102_051 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_220_245_233_C2_034_102_051", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_225_237_234_C2_110_156_144 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_225_237_234_C2_110_156_144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_229_213_242_C2_093_044_112 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_229_213_242_C2_093_044_112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_233_184_230_C2_112_012_242 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_233_184_230_C2_112_012_242", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_236_252_204_C2_157_204_016 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_236_252_204_C2_157_204_016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_237_227_213_C2_135_085_050 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_237_227_213_C2_135_085_050", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_240_236_170_C2_102_072_048 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_240_236_170_C2_102_072_048", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_250_215_246_C2_143_017_057 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_250_215_246_C2_143_017_057", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_250_233_212_C2_171_065_036 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_250_233_212_C2_171_065_036", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_255_204_204_C2_219_000_000 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_255_204_204_C2_219_000_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_255_204_225_C2_199_000_099 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_255_204_225_C2_199_000_099", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_255_204_255_C2_199_000_199 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_255_204_255_C2_199_000_199", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_255_224_224_C2_143_010_010 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_255_224_224_C2_143_010_010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_255_235_204_C2_240_118_005 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_255_235_204_C2_240_118_005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR2_C1_255_255_255_C2_000_000_000 {
            get {
                object obj = ResourceManager.GetObject("CR2_C1_255_255_255_C2_000_000_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
