//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TupleGeo.Resources.Images.ColorRamps.ThreeColors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TupleGeo.Resources.Images.ColorRamps.ThreeColors.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_000_100_100_C2_182_255_143_C3_000_000_255 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_000_100_100_C2_182_255_143_C3_000_000_255", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_000_245_245_C2_000_000_245_C3_245_000_243 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_000_245_245_C2_000_000_245_C3_245_000_243", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_032_204_016_C2_000_242_242_C3_002_032_227 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_032_204_016_C2_000_242_242_C3_002_032_227", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_056_168_000_C2_255_255_000_C3_255_000_000 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_056_168_000_C2_255_255_000_C3_255_000_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_069_117_181_C2_255_255_191_C3_214_047_039 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_069_117_181_C2_255_255_191_C3_214_047_039", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_153_000_000_C2_109_153_086_C3_000_000_153 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_153_000_000_C2_109_153_086_C3_000_000_153", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_182_237_240_C2_031_131_224_C3_009_009_145 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_182_237_240_C2_031_131_224_C3_009_009_145", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_194_082_060_C2_123_237_000_C3_011_044_122 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_194_082_060_C2_123_237_000_C3_011_044_122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_242_241_162_C2_255_000_000_C3_007_029_173 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_242_241_162_C2_255_000_000_C3_007_029_173", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_245_000_000_C2_245_245_000_C3_000_245_000 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_245_000_000_C2_245_245_000_C3_000_245_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_245_245_000_C2_245_122_000_C3_245_000_000 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_245_245_000_C2_245_122_000_C3_245_000_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_255_153_153_C2_212_255_204_C3_153_153_255 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_255_153_153_C2_212_255_204_C3_153_153_255", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_255_200_000_C2_255_000_081_C3_000_000_255 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_255_200_000_C2_255_000_081_C3_000_000_255", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_255_255_128_C2_061_184_104_C3_012_016_120 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_255_255_128_C2_061_184_104_C3_012_016_120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CR3_C1_255_255_128_C2_242_167_046_C3_107_000_000 {
            get {
                object obj = ResourceManager.GetObject("CR3_C1_255_255_128_C2_242_167_046_C3_107_000_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
